const {requireOwner}=require('../../lib/auth');
const {get,post,del,clientGet,clientPost}=require('./client');
function attrs(x){return x?.attributes||{};} function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function viewNode(a){const unlimited=Number(a.memory)===4294967295;return{id:a.id??null,name:a.name??null,uuid:a.uuid??null,memoryMB:unlimited?null:num(a.memory),unlimited,overallocate:num(a.memory_overallocate),diskMB:num(a.disk),cpu:num(a.cpu),allocatedMemoryMB:num(a.allocated_resources?.memory)};}
function viewServer(a){const l=a.limits||{},alloc=a.relationships?.allocations?.data||[];return{id:a.id??null,identifier:a.identifier??null,name:a.name??null,description:a.description??'',status:a.status??null,suspended:!!a.suspended,node:a.node??null,createdAt:a.created_at??null,updatedAt:a.updated_at??null,owner:a.user??null,limits:{memory:num(l.memory)||0,swap:num(l.swap)||0,disk:num(l.disk)||0,cpu:num(l.cpu)||0,io:num(l.io)||0,threads:l.threads??null},allocation:alloc[0]?.attributes||null,allocations:alloc.map(x=>x.attributes||{}),container:a.container??null,egg:a.egg??null,startup:a.startup??null,environment:a.environment??null,featureLimits:a.feature_limits??null,deploy:a.deploy??null};}
async function dashboard(){const[servers,nodes]=await Promise.all([get('/api/application/servers?per_page=100&include=allocations'),get('/api/application/nodes?per_page=100')]);const ss=(servers.data||[]).map(x=>viewServer(attrs(x))),ns=(nodes.data||[]).map(x=>viewNode(attrs(x)));const unlimited=ns.some(n=>n.unlimited),allocated=ss.reduce((t,s)=>t+s.limits.memory,0),finite=ns.filter(n=>!n.unlimited).reduce((t,n)=>t+(n.memoryMB||0),0);return{servers:ss,nodes:ns,capacity:{unlimited,allocatedMemoryMB:allocated,totalMemoryMB:unlimited?null:finite}};}
async function findServer(id){const s=await get(`/api/application/servers/${id}?include=allocations,subusers,databases`);return viewServer(attrs(s));}
module.exports=async(req,res)=>{try{if(!requireOwner(req,res))return;const action=String(req.query?.action||'dashboard').toLowerCase();
if(['dashboard','servers','nodes'].includes(action))return res.json({ok:true,...await dashboard()});
if(action==='server'){const id=Number(req.query?.id);if(!id)return res.status(400).json({ok:false,error:'Server id required'});return res.json({ok:true,server:await findServer(id)});}
if(['suspend','unsuspend','delete'].includes(action)){if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});const id=Number(req.body?.id);if(!id)return res.status(400).json({ok:false,error:'Server id required'});if(action==='delete')await del(`/api/application/servers/${id}`);else await post(`/api/application/servers/${id}/${action}`,{});return res.json({ok:true});}
if(['power','resources','files','file'].includes(action)){const id=Number(req.query?.id||req.body?.id);if(!id)return res.status(400).json({ok:false,error:'Server id required'});const s=await findServer(id);if(!s.identifier)return res.status(400).json({ok:false,error:'Server identifier unavailable'});if(action==='power'){if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});const signal=String(req.body?.signal||'').toLowerCase();if(!['start','stop','restart','kill'].includes(signal))return res.status(400).json({ok:false,error:'Invalid power signal'});await clientPost(`/api/client/servers/${s.identifier}/power`,{signal});return res.json({ok:true,signal});}
if(action==='resources'){const d=await clientGet(`/api/client/servers/${s.identifier}/resources`);return res.json({ok:true,resources:d.attributes||d});}
if(action==='files'){const d=await clientGet(`/api/client/servers/${s.identifier}/files/list?directory=/`);return res.json({ok:true,files:d.data||[]});}
if(action==='file'){const file=String(req.query?.path||'');if(!file)return res.status(400).json({ok:false,error:'File path required'});const d=await clientGet(`/api/client/servers/${s.identifier}/files/contents?file=${encodeURIComponent(file)}`);return res.json({ok:true,content:typeof d==='string'?d:JSON.stringify(d)});}}
return res.status(400).json({ok:false,error:'Unknown action'});}catch(e){console.error('PTERO API ERROR:',e);return res.status(e.status||500).json({ok:false,error:e.message||'Pterodactyl request failed'});}};

