const { requireOwner } = require('../../lib/auth');
const { get, post, del } = require('./client');
function attrs(x){return x?.attributes||{};}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}
function viewNode(a){const unlimited=Number(a.memory)===4294967295;return {id:a.id??null,name:a.name??null,uuid:a.uuid??null,memoryMB:unlimited?null:num(a.memory),unlimited,overallocate:num(a.memory_overallocate),diskMB:num(a.disk),cpu:num(a.cpu),allocatedMemoryMB:num(a.allocated_resources?.memory)};}
function viewServer(a){const l=a.limits||{};const alloc=a.relationships?.allocations?.data||[];return {id:a.id??null,identifier:a.identifier??null,name:a.name??null,description:a.description??'',status:a.status??null,suspended:!!a.suspended,node:a.node??null,createdAt:a.created_at??null,updatedAt:a.updated_at??null,owner:a.user??null,limits:{memory:num(l.memory)||0,swap:num(l.swap)||0,disk:num(l.disk)||0,cpu:num(l.cpu)||0,io:num(l.io)||0,threads:l.threads??null},allocation:alloc[0]?.attributes||null,allocations:alloc.map(x=>x.attributes||{}),container:a.container??null,egg:a.egg??null,startup:a.startup??null,environment:a.environment??null,featureLimits:a.feature_limits??null,deploy:a.deploy??null};}
async function dashboard(){const [servers,nodes]=await Promise.all([get('/api/application/servers?per_page=100&include=allocations'),get('/api/application/nodes?per_page=100')]);const ss=(servers.data||[]).map(x=>viewServer(attrs(x)));const ns=(nodes.data||[]).map(x=>viewNode(attrs(x)));const unlimited=ns.some(n=>n.unlimited);const allocated=ss.reduce((t,s)=>t+s.limits.memory,0);const finite=ns.filter(n=>!n.unlimited).reduce((t,n)=>t+(n.memoryMB||0),0);return {servers:ss,nodes:ns,capacity:{unlimited,allocatedMemoryMB:allocated,totalMemoryMB:unlimited?null:finite}};}
module.exports=async(req,res)=>{try{if(!requireOwner(req,res))return;const action=String(req.query?.action||'dashboard').toLowerCase();
if(action==='dashboard'||action==='servers'||action==='nodes')return res.json({ok:true,...await dashboard()});
if(action==='server'){const id=Number(req.query?.id);if(!id)return res.status(400).json({ok:false,error:'Server id required'});const s=await get(`/api/application/servers/${id}?include=allocations,subusers,databases`);return res.json({ok:true,server:viewServer(attrs(s))});}
if(action==='suspend'||action==='unsuspend'){if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});const id=Number(req.body?.id);if(!id)return res.status(400).json({ok:false,error:'Server id required'});await post(`/api/application/servers/${id}/${action}`,{});return res.json({ok:true});}
if(action==='delete'){if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});const id=Number(req.body?.id);if(!id)return res.status(400).json({ok:false,error:'Server id required'});await del(`/api/application/servers/${id}`);return res.json({ok:true});}
return res.status(400).json({ok:false,error:'Unknown action'});}catch(e){console.error('PTERO API ERROR:',e);return res.status(e.status||500).json({ok:false,error:e.message||'Pterodactyl connection failed'});}};
                                                                                                                                                                                                                                                                         
