const crypto=require('crypto');
const {get,patch,clientPost}=require('./ptero/client');
const {requireOwner,sign}=require('../lib/auth');
const TAG=String(process.env.PANEL_SERVER_TAG||'barbie-panel:v2').trim();
function repoInfo(input){const raw=String(input||'').trim().replace(/\.git$/,'').replace(/\/+$/,'');let m=raw.match(/^https?:\/\/github\.com\/([^/]+)\/([^/#?]+)(?:[?#].*)?$/i);if(!m)m=raw.match(/^github\.com\/([^/]+)\/([^/#?]+)$/i);if(!m)throw Object.assign(new Error('Use a GitHub repository URL like https://github.com/owner/repo'),{status:400});return{owner:m[1],repo:m[2]};}
async function gh(path){const token=String(process.env.GITHUB_TOKEN||'').trim();const r=await fetch('https://api.github.com'+path,{headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10',...(token?{Authorization:`Bearer ${token}`}:{})}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok){const e=new Error(r.status===404?'Repository not found or not accessible. Private repos require GITHUB_TOKEN with Contents: Read.':d?.message||`GitHub ${r.status}`);e.status=r.status;e.github=d;throw e}return d;}
function streamToken(owner,repo,ref,exp){const payload=Buffer.from(JSON.stringify({owner,repo,ref,exp})).toString('base64url');return `${payload}.${sign(payload)}`;}
function readStreamToken(raw){try{const [payload,mac]=String(raw||'').split('.');if(!payload||!mac)return null;const expected=Buffer.from(sign(payload));const actual=Buffer.from(mac);if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))return null;const d=JSON.parse(Buffer.from(payload,'base64url').toString());if(!d.exp||Date.now()>d.exp)return null;return d;}catch{return null;}}
async function serverRaw(id){const d=await get(`/api/application/servers/${id}`);const a=d?.attributes||{};const owned=String(a.description||'').includes(`[${TAG}]`)||String(a.external_id||'').startsWith(`${TAG}:`);if(!owned)throw Object.assign(new Error('Server is not managed by this hosting panel'),{status:403});return a;}
module.exports=async(req,res)=>{try{
const action=String(req.query?.action||'info').toLowerCase();
if(action==='stream'){const d=readStreamToken(req.query?.token);if(!d)return res.status(403).end('Invalid or expired import link');const token=String(process.env.GITHUB_TOKEN||'').trim();const ref=String(d.ref||'main');const u=`https://api.github.com/repos/${encodeURIComponent(d.owner)}/${encodeURIComponent(d.repo)}/tarball/${encodeURIComponent(ref)}`;const r=await fetch(u,{headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10','User-Agent':'Barbie-Hosting-Panel',...(token?{Authorization:`Bearer ${token}`}:{})}});if(!r.ok)return res.status(r.status).end('GitHub archive unavailable');res.statusCode=200;res.setHeader('Content-Type','application/gzip');res.setHeader('Cache-Control','private, no-store');if(r.body)for await(const chunk of r.body)res.write(Buffer.from(chunk));return res.end();}
if(!requireOwner(req,res))return;
const body=req.body||{};
if(action==='info'){const {owner,repo}=repoInfo(body.url||req.query?.url);const d=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`);const b=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/branches?per_page=100`);return res.json({ok:true,repository:{fullName:d.full_name,name:d.name,private:!!d.private,defaultBranch:d.default_branch,description:d.description||'',htmlUrl:d.html_url,sizeMB:d.size,branches:(b||[]).map(x=>x.name)},privateAccess:!!String(process.env.GITHUB_TOKEN||'').trim()});}
if(action==='deploy'){if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});if(!String(process.env.PTERO_CLIENT_API_KEY||'').trim())return res.status(503).json({ok:false,error:'PTERO_CLIENT_API_KEY is required for GitHub deployment'});const {owner,repo}=repoInfo(body.url);const id=Number(body.serverId);if(!id)return res.status(400).json({ok:false,error:'Target server is required'});const s=await serverRaw(id);const d=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`);const branch=String(body.branch||d.default_branch||'main').trim();const token=String(process.env.GITHUB_TOKEN||'').trim();if(d.private&&!token)return res.status(400).json({ok:false,error:'This repository is private. Configure GITHUB_TOKEN on Vercel with Contents: Read permission.'});const deployId=crypto.randomBytes(8).toString('hex');const archive=`.barbie-github-${deployId}.tar.gz`;const stream=streamToken(owner,repo,branch,Date.now()+5*60*1000);const base=`${req.headers['x-forwarded-proto']||'https'}://${req.headers.host}`;const proxy=`${base}/api/github?action=stream&token=${encodeURIComponent(stream)}`;await clientPost(`/api/client/servers/${s.identifier}/files/pull`,{url:proxy,directory:'/',filename:archive});
const start=String(body.startCommand||'npm start').trim()||'npm start';const install=String(body.installCommand||'').trim();const deployDir='.barbie-app';const setup=`for i in $(seq 1 90); do [ -f /home/container/${archive} ] && break; sleep 2; done; if [ -f /home/container/${archive} ]; then mkdir -p /home/container/${deployDir}; tar -xzf /home/container/${archive} --strip-components=1 -C /home/container/${deployDir}; rm -f /home/container/${archive}; fi; cd /home/container/${deployDir}; if [ -f package-lock.json ]; then npm ci; elif [ -f package.json ]; then npm install; fi; ${install?install+'; ':''}${start}`;
await patch(`/api/application/servers/${id}/startup`,{startup:setup,environment:s.environment||{},egg:Number(s.egg?.id||s.egg||0),image:s.container?.image||undefined,skip_scripts:false});let started=false,startError=null;try{await clientPost(`/api/client/servers/${s.identifier}/power`,{signal:'restart'});started=true}catch(e){startError=e.message}
return res.json({ok:true,repository:d.full_name,private:!!d.private,branch,server:{id:s.id,identifier:s.identifier},deploymentId:deployId,queued:true,started,startError,folder:`/${deployDir}`,note:'The panel queues a secure GitHub archive download. The server startup waits for the archive, extracts it into .barbie-app, installs Node dependencies, then runs the configured start command.'});}
return res.status(400).json({ok:false,error:'Unknown action'});
}catch(e){return res.status(e.status||500).json({ok:false,error:e.message||'GitHub operation failed'});}};
