const {requireOwner}=require('../lib/auth');
const {get,patch,clientPost}=require('./ptero/client');
const TAG=String(process.env.PANEL_SERVER_TAG||'barbie-panel:v2').trim();
function repoInfo(input){const raw=String(input||'').trim().replace(/\.git$/,'').replace(/\/+$/,'');let m=raw.match(/^https?:\/\/github\.com\/([^/]+)\/([^/#?]+)(?:[?#].*)?$/i);if(!m)m=raw.match(/^github\.com\/([^/]+)\/([^/#?]+)$/i);if(!m)throw Object.assign(new Error('Use a GitHub repository URL like https://github.com/owner/repo'),{status:400});return{owner:m[1],repo:m[2]};}
async function gh(path){const token=String(process.env.GITHUB_TOKEN||'').trim();const r=await fetch('https://api.github.com'+path,{headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10',...(token?{Authorization:`Bearer ${token}`}:{})}});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok){const e=new Error(d?.message||`GitHub ${r.status}`);e.status=r.status;e.github=d;throw e}return d;}
async function serverRaw(id){const d=await get(`/api/application/servers/${id}`);const a=d?.attributes||{};if(!String(a.description||'').includes(`[${TAG}]`))throw Object.assign(new Error('Server is not managed by this hosting panel'),{status:403});return a;}
module.exports=async(req,res)=>{try{if(!requireOwner(req,res))return;const action=String(req.query?.action||'info').toLowerCase();const body=req.body||{};
if(action==='info'){const {owner,repo}=repoInfo(body.url||req.query?.url);const d=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`);const b=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/branches?per_page=100`);return res.json({ok:true,repository:{fullName:d.full_name,name:d.name,private:!!d.private,defaultBranch:d.default_branch,description:d.description||'',htmlUrl:d.html_url,sizeMB:d.size,branches:(b||[]).map(x=>x.name)}});}
if(action==='deploy'){if(req.method!=='POST')return res.status(405).json({ok:false,error:'POST required'});const {owner,repo}=repoInfo(body.url);const id=Number(body.serverId);if(!id)return res.status(400).json({ok:false,error:'Target server is required'});const s=await serverRaw(id);const d=await gh(`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`);const branch=String(body.branch||d.default_branch||'main').trim();const start=String(body.startCommand||'npm start').trim();if(!start)return res.status(400).json({ok:false,error:'Start command is required'});const token=String(process.env.GITHUB_TOKEN||'').trim();if(d.private&&!token)return res.status(400).json({ok:false,error:'This repository is private. Configure GITHUB_TOKEN on Vercel with Contents: Read permission.'});
const env={...(s.environment||{}),GITHUB_REPO:`${owner}/${repo}`,GITHUB_BRANCH:branch,GITHUB_TOKEN:token};
const startup=`if [ -n "${'${GITHUB_TOKEN}'}" ]; then printf "https://x-access-token:${'${GITHUB_TOKEN}'}@github.com\\n" > ~/.git-credentials; git config --global credential.helper store; fi; if [ ! -d .git ]; then git clone --branch "${'${GITHUB_BRANCH}'}" "https://github.com/${'${GITHUB_REPO}'}.git" .; else git fetch origin "${'${GITHUB_BRANCH}'}" && git reset --hard "origin/${'${GITHUB_BRANCH}'}"; fi; rm -f ~/.git-credentials; git config --global --unset credential.helper 2>/dev/null || true; if [ -f package.json ]; then npm install; fi; ${start}`;
await patch(`/api/application/servers/${id}/startup`,{startup,environment:env,egg:Number(s.egg?.id||s.egg||0),image:s.container?.image||undefined,skip_scripts:false});
let started=false;let startError=null;try{await clientPost(`/api/client/servers/${s.identifier}/power`,{signal:'restart'});started=true}catch(e){startError=e.message}
return res.json({ok:true,repository:d.full_name,private:!!d.private,branch,startCommand:start,started,startError:started?null:startError,note:'Server startup was configured to clone/update the repository and run the start command.'});}
return res.status(400).json({ok:false,error:'Unknown action'});}catch(e){return res.status(e.status||500).json({ok:false,error:e.message||'GitHub operation failed'});}};
